# Generated by Django 5.1.3 on 2024-12-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('uri', models.CharField(max_length=255)),
                ('mini_photo', models.ImageField(blank=True, null=True, upload_to='auction_photos/')),
                ('status', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('offer', models.FloatField()),
                ('date', models.DateTimeField()),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auctionitem')),
            ],
        ),
    ]
