# Generated by Django 5.1.3 on 2024-12-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='mini_photo',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='auction_photos/'),
        ),
    ]
