# Generated by Django 5.1.3 on 2024-12-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auctionitem_mini_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='mini_photo',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='auction_photos/'),
        ),
    ]
